version: '3.8'

services:
  yt-backend:
    build: 
      context: ./backend
    container_name: curator_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./backend/temp_downloads:/app/temp_downloads

  yt-frontend:
    build:
      context: ./frontend
    container_name: curator_frontend
    restart: always
    ports:
      - "8085:80"
    depends_on:
      - yt-backend
